package ca.ualberta.compileorcry;

import com.google.firebase.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * TimestampHelper class provides a utility method to create Firebase Timestamp objects
 * from date strings in the format "yyyy-MM-dd". Made for generating timestamps for moods
 * generated by FeedTest.java
 */

public class TimestampHelper {
    public static Timestamp createTimestamp(String dateString) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        try {
            Date date = sdf.parse(dateString); // Convert string to Date
            return new Timestamp(date); // Convert Date to Firebase Timestamp
        } catch (ParseException e) {
            e.printStackTrace();
            return null; // Handle error
        }
    }
}

